### ISSUE TITLE
Update vr-solitaire privacy policy 

### ISSUE THREAD

**Issue by johnweland** [DamnedCatStudio/damnedcatstudio.github.io#26]
We need to update the Privacy Policy for the `vr-solitaire` game in `/legal/games/vr-solitaire/privacy` to lay plain what data we collect, [none], and how to opt-out or delete it [the app]

**Comment by Gausroth** [comment]
Update the following line:

<li><strong>We Don&apos;t:</strong> Solitaire does not collect any data other than the usage data polled from Oculus itself.</li>

to read:

<li><strong>We Don&apos;t:</strong> VR Solitaire does not collect any data other than the usage data polled from Oculus itself.</li>

Other than that it looks good.

**Comment by johnweland** [comment]
closed #27
